SELECT
    O.ORDER_ID,
    O.ORDER_DATETIME,
    O.CUSTOMER_ID,
    O.ORDER_STATUS,
    O.STORE_ID,
    (
SELECT
    SUM(UNIT_PRICE * QUANTITY)
FROM
    ORDER_ITEMS I
WHERE
    I.ORDER_ID = O.ORDER_ID
    ) TOTAL
FROM
    ORDERS O
WHERE
    ORDER_ID = :P16_ORDER